# Site settings
title: Moodle composer repository
email: micaherne@blueyonder.co.uk
description: > # this means to ignore newlines until "baseurl:"
  This is an experimental Composer repository for Moodle
  and its plugin database.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://micaherne.github.io/moodle-plugin-repo" # the base hostname & protocol for your site
twitter_username: michael_aherne
github_username:  micaherne

# Build settings
markdown: kramdown
